// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
  defaultTemplateId: 'default', //This is the default template for 2 args1
  defaultAltTemplateId: 'defaultAlt', //This one for 1 arg
  templates: {
    //You can add static templates here
    default:
      '<div style="word-break: break-all; padding: 0.35vw; background-color: rgba({2}, {3}, {4}, 0.6); border-radius: 3px;"><i class="{5}"></i> <b style="color: rgb({6}, {7}, {8});">{0}:</b> {1}</div>',
    pixel:
      '<div style="word-break: break-all; padding: 0.6vw; margin: 5px; background-color: rgba({2}, {3}, {4}, 0.75); border-radius: 10px; font-weight: 600; font-family: "Lato", Helvetica, Arial, sans-serif!important; text-shadow: 0px 0px 0px white!important;"> <span style="font-weight: 900;!important; font-family: "Lato", Helvetica, Arial, sans-serif!important; text-shadow: 0px 0px 0px white!important; font-size: 1rem;">[{0}]:</span> {1}</div>',
    defaultAlt: '{0}',
    print:
      '<pre style="font-family: Consolas, Menlo, Monaco, Lucida Console, Liberation Mono,DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif;">{0}</pre>',
    'example:important': '<h1>^2{0}</h1>',
  },
  fadeTimeout: 10000,
  suggestionLimit: 20,
  style: {
    background: 'rgba(155, 155, 155, 0)',
    width: '30%',
    height: '25%',
  },
};

window.addEventListener('message', function (event) {
  if (event.data.type == 'hide') {
    document.getElementById('app').children[0].style.display = 'none';
  } else if (event.data.type == 'show') {
    document.getElementById('app').children[0].style.display = 'block';
  }
});
